stages:
  - build
  - deploy

build:
  stage: build
  tags:
   - build
  only:
    - main
  cache:
    paths:
      - node_modules
      - vendor
  before_script:
    - docker-compose --project-name lainit-website up -d --build
  script:
    - mkdir -p storage/framework/{sessions,views,cache}
    - docker-compose --project-name lainit-website exec -T --user vvuser tooling composer install --optimize-autoloader --no-interaction
    - docker-compose --project-name lainit-website exec -T --user vvuser tooling npm ci
    - docker-compose --project-name lainit-website exec -T --user vvuser tooling gulp

deploy:
  environment:
    DOMAIN: https://vvcode.visuel.dev
  stage: deploy
  tags:
    - deploy
  only:
    - main
  variables:
    GIT_STRATEGY: none
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - docker-compose --project-name lainit-website exec -T --user vvuser tooling composer install --optimize-autoloader --no-interaction --no-dev
  script:
    - eval `ssh-agent -s`
    - ssh-add
    - >
      ssh $SERVER_USER@$HOST "
        cd $DOMAIN && php artisan down
      "
    - >
      rsync -av -e "ssh" --delete --exclude="public/storage"
      app bootstrap config database public routes resources vendor artisan
      $SERVER_USER@$HOST:$SERVER_PATH/$DOMAIN
    - >
      rsync -av -e "ssh"
      .env.production
      $SERVER_USER@$HOST:$SERVER_PATH/$DOMAIN/.env
    - >
      rsync -av -e "ssh"
      composer.json
      $SERVER_USER@$HOST:$SERVER_PATH/$DOMAIN
    - >
      ssh $SERVER_USER@$HOST "
        cd $DOMAIN &&
        php artisan migrate --force &&
        php artisan optimize:clear &&
        php artisan optimize &&
        php artisan up
      "
